[build]
  command = "CI= npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://<wantsun>.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
